### ISSUE TITLE
Hitscan ON Problem

### ISSUE THREAD

**Issue by atleastutried** [mrflashstudio/osu-rx#1]
when i turn on hitscan, the rx hit normally just sliders and sometimes a streams, completely outside of 
rhythm, this is that's just when i turn on hitscan.

**Comment by mrflashstudio** [comment]
Do you have raw input on? If so, try turning it off and see if it helps.

**Comment by atleastutried** [comment]
No, i don't play with raw input on

**Comment by mrflashstudio** [comment]
That's strange then. Can you send me a video or an osu replay of you playing with hitscan on?

**Comment by atleastutried** [comment]
I think i can, send me your discord its more easy i think

**Comment by atleastutried** [comment]
nvm i think this is work, https://cdn.discordapp.com/attachments/321432254599528449/690326267278786560/-_OISHII_-_ONIGIRI_FREEWAY_ANOTHER_2020-03-19_Osu.osr

**Comment by mrflashstudio** [comment]
Thanks. Can you confirm that changing value of "H_EnablePrediction" from True to False in config.ini file doesn't help? (you should restart osu!rx after doing so though)

**Comment by atleastutried** [comment]
If i make this the rx not work with Hitscan Enabled

**Comment by mrflashstudio** [comment]
Thanks. Try to play with hitscan again on new release - https://github.com/mrflashstudio/osu-rx/releases/tag/1.1.0-hitscan-test-2 (don't forget to change "H_EnablePrediction" back to True)

**Comment by atleastutried** [comment]
No :(, the same problem, i try again with "H_EnablePrediction" False and True, but not work

**Comment by atleastutried** [comment]
Maybe the problem is just with me ?

**Comment by mrflashstudio** [comment]
I hope it's not, it would only make thing harder. Can you please test in other display modes (fullscreen, borderless, windowed (800x600 preferably)) and see if there will be any changes? If not, then i'll make and send you special build today or tomorrow to troubleshoot you.

**Comment by mrflashstudio** [comment]
A little bit early, but i made you a "troubleshooting tool" in case the advice above didn't helped.
Launch osu!, then run this tool. Switch osu!'s display mode to borderless fullscreen. 
![image](https://user-images.githubusercontent.com/24892085/77208723-7c288a80-6b0d-11ea-9cd6-f045ceaf899b.png)
Alt+tab back to the tool. Move the cursor to the top-right corner of your screen and then make a screenshot so i can see the console window, do the same thing for bottom-left corner of your screen. 
![image](https://user-images.githubusercontent.com/24892085/77208846-cd387e80-6b0d-11ea-9bd7-bed555b15276.png)
Now go back to osu!, switch to windowed 800x600 and do the same thing, as above. Send those 4 screenshots to me through github. You can crop the screenshots if you don't want me to see what else is happening on your pc at the given moment.
[rx.zip](https://github.com/mrflashstudio/osu-rx/files/4361882/rx.zip)

**Comment by atleastutried** [comment]
holy dude sorry for the delay in responding and do you have to do all this thing :(, i play with 1280x720 but with Render at native resolution so looks like a fullscreen bordelees, i turn this off and the hitscan is working fine, thanks for the pacience and the helping, u are a fuck good guy <3

**Comment by atleastutried** [comment]
btw congrats with de osu!rx,

**Comment by atleastutried** [comment]
its working now but, apparently sometimes the rx hit late, i can hit some things with the relax from osu, but with the osu!rx no, i don't know why but its just some feedback for you, good job !

**Comment by mrflashstudio** [comment]
Oh, i haven't tested osu!rx with "render at native resolution" turned on, so it's most likely the problem on osu!rx side, I'll take a look at that tomorrow. Thanks for helping me test this before official release ;)

**Comment by atleastutried** [comment]
np bro :)

**Comment by SweetofBiscuit** [comment]
Чел, потестил я хитскан, он неплох вот только он мисает больше чем если без хитскана играть, на стрим картах это очень плохо работает, сорян если чет не понял

**Comment by mrflashstudio** [comment]
Создай отдельный issue, если у тебя есть какие либо предложения по улучшению хитскана. И пожалуйста, обычные разговоры ограничь моей темой на mpgh. Спасибо. А вообще, он наоборот должен лучше на стримах работать, при условии, что ты аимишь более-менее ровно.

**Comment by mrflashstudio** [comment]
Will close and create separate issue for this. I won't be able to fix this before official release anyways.
