### ISSUE TITLE
Signature scanning takes too long

### ISSUE THREAD

**Issue by mrflashstudio** [mrflashstudio/osu-rx#10]
Memory scanning takes ~20.5s on my machine

**Comment by DeadHunterX20** [comment]
Before the Memory scanning process was taking something around 15s for me but now it just stuck, i even waited 5 minutes but still is stuck

**Comment by DeadHunterX20** [comment]
So after i wait it just stay at this (second screenshot) and if i click enter i get this (first screenshot).

![Przechwytywanie1](https://user-images.githubusercontent.com/64276871/80409611-74f15b00-88c9-11ea-93ef-9210cffaca0d.PNG)
![Przechwytywanie](https://user-images.githubusercontent.com/64276871/80409616-76228800-88c9-11ea-8cb3-194ebcdeaa36.PNG)

**Comment by mrflashstudio** [comment]
Oops, this shouldn't have happened. Please try again on the latest commit (5042895). I'm also interested in whether memory scanning will fail or not this time.

**Comment by DeadHunterX20** [comment]
So i checked it with the latest commit and now after like 4 seconds i got this 
![Przechwytywanie](https://user-images.githubusercontent.com/64276871/80420628-57c58800-88db-11ea-98c8-ac8bae73316c.PNG)

**Comment by mrflashstudio** [comment]
Currently figuring out the cause, i may have to delay new update, sorry for that...

**Comment by mrflashstudio** [comment]
Seems like this was somehow fixed by the last few commits..? (now memory scanning takes only 2.5s on my machine). Closing for now.

**Comment by mrflashstudio** [comment]
Seems i was just lucky, still reproducible

**Comment by DeadHunterX20** [comment]
I checked a few times and it was working for me just fine (3-5s to load)

**Comment by CoomerOsu** [comment]
everything is good for me, and it was good before never had a problem.

**Comment by mrflashstudio** [comment]
Signature scanning now takes 5-7.5s which is ~60-70% better than 1.1.2 (15-20s). I consider this resolved.

**Comment by HoLLy-HaCKeR** [comment]
Can still be improved in some ways, ill send a PR with some improvements.
