### ISSUE TITLE
osu!rx should use more OOP-like memory access style

### ISSUE THREAD

**Issue by mrflashstudio** [mrflashstudio/osu-rx#12]
All fields that osu!rx reads from memory are either from GameBase or Player. It's a pain in the ass to update tons of signatures, so having just two will make my life way easier.

**Comment by Azukee** [comment]
is reading objects from memory a goal?
because it can easily be achieved when expanding the OOP classes

**Comment by mrflashstudio** [comment]
i'm not sure if i understood you correctly, but the goal (at least how i see it) is to have a base address of some class and offset from it to get needed fields, not reading the whole object

**Comment by Azukee** [comment]
is reading _hitobjects_ from memory a goal, my bad
cuz im creating oop clases for osu rn and have a HitObjectManager working

**Comment by mrflashstudio** [comment]
oh, yeah, reading hitobjects from memory would be a good thing and should happen at some moment, but it's not necessarily a high priority
