### ISSUE TITLE
Stacking isn't accounted

### ISSUE THREAD

**Issue by mrflashstudio** [mrflashstudio/osu-rx#17]
Hitscan misses all stacks completely due to unexistent stacking implementation.

**Comment by Azukee** [comment]
Just gonna reference [this](https://github.com/mrflashstudio/osu-rx/issues/12#issuecomment-622379550) here 
> oh, yeah, reading hitobjects from memory would be a good thing and should happen at some moment, but it's not necessarily a high priority

Reading HitObjects from memory would completely remove any need to create any calculation for HitObjects in the bot itself, as osu! does it all by itself.

**Comment by mrflashstudio** [comment]
yeah i know about that, but it still needs to be implemented for ipc fallback mode (although i may consider dropping it's support since it's starting to get messier and messier each update)

**Comment by mrflashstudio** [comment]
resolved in 2247bc1

**Comment by Azukee** [comment]
Good job on 2247bc1 
uwu
