### ISSUE TITLE
readme they  say

### ISSUE THREAD

**Issue by Quadec** [mrflashstudio/osu-rx#21]
read the read me and i have that downloaded already there isnt a .exe and when i  build the solution there is errors 
![image](https://user-images.githubusercontent.com/62908539/82449612-67338d80-9aa3-11ea-93a6-e0157a5a80d3.png)

and closing a issue wont be good cuz then we have to make more and it wont look good if u keep closing issues

**Comment by mrflashstudio** [comment]
Please learn to read, thank you
![image](https://user-images.githubusercontent.com/24892085/82449965-b46c2b00-9ab4-11ea-8938-43189492434e.png)
