### ISSUE TITLE
SINGLE TAP ISSUE

### ISSUE THREAD

**Issue by bakasensei24** [mrflashstudio/osu-rx#24]
I just noticed that a single tap looks like tapping with AUTO MOD.

--SLIDER TAP ISSUE----
*It will alternate if the slider has stack another slider.
*Fast Slider Velocity alternates

*REPEAT SLIDER TAP ISSUE*
*Stacks of Repeat Slider Alternates
*Alternates when there are Repeat Sliders near them.

EXAMPLE: TECH MAPS SLIDERS ARE being alternated... I suggest it must only use a single tap

**Comment by mrflashstudio** [comment]
I guess this is now much better after a9e8a27 ? Please test by changing "Slider alternation binding" to "StartTime" in relax settings. Can't test it easily myself, because you didn't provided any beatmaps.

**Comment by bakasensei24** [comment]
Alternation Binding Setting Fix
Works on TECH MAPS
