### ISSUE TITLE
Duplicate "* slider.Repeats % 1"

### ISSUE THREAD

**Issue by xxCherry** [mrflashstudio/osu-rx#25]
I don't know it's bug or not, so leave it here. Sorry if something wrong.

Why do you wrote `* slider.Repeats % 1` on
https://github.com/mrflashstudio/osu-rx/blob/c2a25af5e3bff303519c06a1fb7c4d13327753c9/osu!rx/Core/Relax/Objects/SliderPath.cs#L60

If it's already in ProgressAt method.

https://github.com/mrflashstudio/osu-rx/blob/c2a25af5e3bff303519c06a1fb7c4d13327753c9/osu!rx/Core/Relax/Objects/SliderPath.cs#L43

**Comment by mrflashstudio** [comment]
Yeah, looks like a duplicate to me. Thanks for pointing this out!
