### ISSUE TITLE
Parsing keys directly from memory.

### ISSUE THREAD

**Issue by xxCherry** [mrflashstudio/osu-rx#26]
**Describe your proposal**
Parsing keys directly from memory. Let users only change order of keys.
e.g: Primary=K1 or M1
      Secondary=K2 or M2

**Why do you think your solution is better?:**
That's will be make things a bit easier for users who change their buttons and just would be cool.

That's all.

**Comment by mrflashstudio** [comment]
Thanks for a nice suggestion! This change changes value type of some settings, so make sure to remove the old config.ini file to avoid crashes!
