### ISSUE TITLE
BindingManager needs a better signature

### ISSUE THREAD

**Issue by mrflashstudio** [mrflashstudio/osu-rx#27]
**Expected behavior:**
osu!rx should initialize without any errors

**Actual behavior:**
osu!rx fails to scan for BindingManager pointer

**Steps to Reproduce:**
1. Launch osu!
2. DO NOT touch anything, do not press any buttons
3. Launch osu!rx
4. Enjoy the error

**Additional info:**
Memory scan will succeed only if you're already in song select, pressed some keys or opened settings/bindings.

**Environment:**
- osu!rx version: github 5f4d51a

**Comment by HoLLy-HaCKeR** [comment]
sounds like the code you're scanning for just hasn't been jitted yet

**Comment by mrflashstudio** [comment]
also, hey holly, lw. it's nice seeing you guys here ;)
