### ISSUE TITLE
How can i change the timing of the hitscan, so i dont miss jumps?

### ISSUE THREAD

**Issue by Goalerzz** [mrflashstudio/osu-rx#30]
Hey! :D

So basically, every time i dont time the jumps perfectly, lets say, on a 6* map, it doesnt hit it. So, normal rx of osu is **a bit faster timed** than in yours. So can you please tell me how i could maybe change it so i can play jump maps aswell, cuz they are very hard to hit with the later timing. If its not implemented, can you please put like a **"hitscan timing"** or **"hitscan timing range"** so you could change the timing of the hits by whatever value you want. Thank you, please help me D:

:)

**Comment by mrflashstudio** [comment]
Are you using MPGH build or compiled source code from github yourself?

**Comment by Goalerzz** [comment]
I have no experience in coding, sorry, i just downloaded it from your yt video and thought i missed a setting or something. :(

**Comment by Goalerzz** [comment]
I downloaded it from mpgh, i just wanna know how i could change (if possible) the timing of the hitscan

**Comment by mrflashstudio** [comment]
The issue you described is already fixed here on github and will be available on MPGH later this month. There is no workaround so you just have to wait, sorry.

**Comment by Goalerzz** [comment]
Ok thanks :)
Im thrilled to see the update soon, please release it soon! :D
