### ISSUE TITLE
Stuck on Idle

### ISSUE THREAD

**Issue by ComIReA** [mrflashstudio/osu-rx#32]
**Expected behavior:**
Not to be stuck on idle

**Actual behavior:**
stuck on idle

**Steps to Reproduce:**
Pressed Start

**Screenshots or videos showing encountered issue:**
https://gyazo.com/8166f4d1c3636e87f26d55d248a026f4
https://gyazo.com/97fdb08ad37a40b353f2cb3b2626d894

**Additional info:**

**Environment:**
- osu!rx version: 1.2
1.12 works fine so I dont know any way to fix the issue

**Comment by mrflashstudio** [comment]
Switch to cutting edge release stream. Follow [this link](https://www.mpgh.net/forum/showthread.php?t=1488076&p=14860127&viewfull=1#post14860127) if you don't know how to do that.
