### ISSUE TITLE
virus detection

### ISSUE THREAD

**Issue by mc360master** [mrflashstudio/osu-rx#33]
windows virus detection detects this as Trojan:Win32/Bomitag.D!ml. does this mean the software is harmful?

**Comment by mrflashstudio** [comment]
no
https://www.virustotal.com/gui/file/9243931bcccf614329c905a63635a2e27b09c9d52d43b68e4dcfcaa2f53cb9c2/detection
https://virusscan.jotti.org/en-US/filescanjob/awsp3nkf8s
